import { QueryModuleInfo, QueryModuleType } from '../types';

export const QUERY_MODULES: QueryModuleInfo[] = [
  {
    id: 'cpf_1',
    title: 'CPF 1',
    subtitle: '(Basíca)',
    category: 'Pessoa Física',
    placeholder: '000.000.000-00',
    iconName: 'UserCheck',
    badge: 'Basíca',
    description: 'Validação cadastral na Receita Federal, Nome Completo, Situação Cadastral, Data de Nascimento e Nome da Mãe.',
    defaultSample: '341.892.518-20',
  },
  {
    id: 'cpf_2',
    title: 'CPF 2',
    subtitle: '(Intermediária)',
    category: 'Pessoa Física',
    placeholder: '000.000.000-00',
    iconName: 'ShieldAlert',
    badge: 'Intermediária',
    description: 'Dossiê cadastral + Score Serasa/Boa Vista, Telefones vinculados, Endereços históricos, E-mails e Renda estimada.',
    defaultSample: '528.190.432-88',
  },
  {
    id: 'cpf_3',
    title: 'CPF 3',
    subtitle: '(Avançada)',
    category: 'Pessoa Física',
    placeholder: '000.000.000-00',
    iconName: 'Fingerprint',
    badge: 'Avançada',
    description: 'Investigação profunda: Vínculos societários (QSA), Veículos no Detran, Processos Judiciais (Tribunais), Parentescos e Bens.',
    defaultSample: '912.445.871-04',
  },
  {
    id: 'cnpj',
    title: 'CNPJ',
    subtitle: 'Empresarial & QSA',
    category: 'Pessoa Jurídica',
    placeholder: '00.000.000/0000-00',
    iconName: 'Building2',
    badge: 'Corporativo',
    description: 'Razão Social, Nome Fantasia, CNAE Principal/Secundário, Capital Social, Sócios e Administradores (QSA) e Situação Fiscal.',
    defaultSample: '18.236.120/0001-58',
  },
  {
    id: 'nome',
    title: 'NOME',
    subtitle: 'Localização & Homônimos',
    category: 'Pessoa Física',
    placeholder: 'Digite o nome completo da pessoa...',
    iconName: 'Users',
    badge: 'Identificação',
    description: 'Busca fonética nacional para identificação de CPF, UF de registro, prováveis homônimos e última localização conhecida.',
    defaultSample: 'CARLOS EDUARDO DE ALMEIDA SILVA',
  },
  {
    id: 'email',
    title: 'E-MAIL',
    subtitle: 'Vínculos & Breaches',
    category: 'Veículos & Contato',
    placeholder: 'exemplo@empresa.com.br',
    iconName: 'Mail',
    badge: 'Cyber Intel',
    description: 'Identificação de titularidade do domínio/e-mail, redes sociais vinculadas, presença em vazamentos de dados e empresas associadas.',
    defaultSample: 'investigacoes.contato@nexuslog.com.br',
  },
  {
    id: 'placa',
    title: 'PLACA',
    subtitle: 'Histórico Veicular',
    category: 'Veículos & Contato',
    placeholder: 'ABC1D23 ou ABC-1234',
    iconName: 'CarFront',
    badge: 'Veicular',
    description: 'Marca, Modelo, Ano/Fabricação, Chassi, Renavam, Situação de Roubo/Furto, Restrições Financeiras (Gravame) e Débitos.',
    defaultSample: 'BRA2E19',
  },
  {
    id: 'telefone',
    title: 'TELEFONE',
    subtitle: 'Operadora & Titular',
    category: 'Veículos & Contato',
    placeholder: '(11) 98765-4321',
    iconName: 'PhoneCall',
    badge: 'Telefonia',
    description: 'Operadora atual, histórico de portabilidade, titularidade presumida de linha, tipo (Fixo/Móvel) e geolocalização do DDD.',
    defaultSample: '(11) 98452-1920',
  },
];
