import { QueryModuleType } from '../types';

export interface ProModuleInfo {
  id: QueryModuleType;
  title: string;
  subtitle: string;
  command: string;
  placeholder: string;
  badge: string;
  iconName: string;
  description: string;
  defaultSample: string;
  inputLabel: string;
  inputHelper: string;
  inDevelopment?: boolean;
}

export const PRO_MODULES: ProModuleInfo[] = [
  {
    id: 'pro_cpf',
    title: 'CPF Pro',
    subtitle: 'Dados cadastrais e inteligência financeira',
    command: '/cpf',
    placeholder: '12345678901',
    badge: 'EM DESENVOLVIMENTO',
    iconName: 'UserCheck',
    description: 'Módulo em desenvolvimento e aprimoramento de inteligência.',
    defaultSample: '12345678901',
    inputLabel: 'CPF do Alvo',
    inputHelper: 'Módulo temporariamente em desenvolvimento.',
    inDevelopment: true,
  },
  {
    id: 'pro_telefone',
    title: 'Telefone Pro',
    subtitle: 'Vínculos do telefone com pessoas (CPF, Mãe, Renda)',
    command: '/telefone',
    placeholder: '11999887766',
    badge: 'EM DESENVOLVIMENTO',
    iconName: 'PhoneCall',
    description: 'Módulo em desenvolvimento e aprimoramento de inteligência.',
    defaultSample: '11999887766',
    inputLabel: 'Número com DDD',
    inputHelper: 'Módulo temporariamente em desenvolvimento.',
    inDevelopment: true,
  },
  {
    id: 'pro_nome',
    title: 'Nome Pro',
    subtitle: 'Busca pessoas pelo nome (CPF, Nasc., Local)',
    command: '/nome',
    placeholder: 'Joao Silva Ramos',
    badge: 'VARREDURA',
    iconName: 'Users',
    description: 'Varredura fonética nacional, localização de CPF, grau de parentesco, data de nascimento e filiação.',
    defaultSample: 'Joao Silva Ramos',
    inputLabel: 'Nome Completo',
    inputHelper: 'Informe o nome completo para busca (ex: Joao Silva Ramos)',
  },
  {
    id: 'pro_email',
    title: 'E-mail Pro',
    subtitle: 'Vínculos do email + Score de qualidade',
    command: '/email',
    placeholder: 'usuario@dominio.com',
    badge: 'CYBER INTEL',
    iconName: 'Mail',
    description: 'Identificação de titularidade, cruzamento com bases de data breach, senhas expostas e redes vinculadas.',
    defaultSample: 'usuario@dominio.com',
    inputLabel: 'Endereço de E-mail',
    inputHelper: 'E-mail para investigação (ex: usuario@dominio.com)',
  },
  {
    id: 'pro_endereco',
    title: 'Endereço Pro',
    subtitle: 'Moradores do endereço/CEP',
    command: '/endereco',
    placeholder: '01310100 ou SAO PAULO SP',
    badge: 'GEO LOCALIZAÇÃO',
    iconName: 'MapPin',
    description: 'Relação de residentes no imóvel, linhas telefônicas registradas e empresas sediadas no endereço.',
    defaultSample: '01310100',
    inputLabel: 'Endereço ou CEP',
    inputHelper: 'Informe o CEP numérico (01310100) ou Cidade/UF (ex: SAO PAULO SP)',
  },
  {
    id: 'pro_cep',
    title: 'CEP Pro',
    subtitle: 'Logradouro, bairro, cidade, UF',
    command: '/cep',
    placeholder: '01310100',
    badge: 'LOGRADOURO',
    iconName: 'Compass',
    description: 'Dados detalhados do CEP, empresas ativas no logradouro, código IBGE e mapeamento de residentes.',
    defaultSample: '01310100',
    inputLabel: 'Código Postal (CEP)',
    inputHelper: '8 dígitos numéricos sem hífen (ex: 01310100)',
  },
  {
    id: 'pro_cnpj',
    title: 'CNPJ Pro',
    subtitle: 'Razão social, sócios, situação',
    command: '/cnpj',
    placeholder: '12345678000190',
    badge: 'CORPORATIVO',
    iconName: 'Building2',
    description: 'Sócios administradores, percentual societário, capital social, faturamento presumido e certidão de dívidas.',
    defaultSample: '12345678000190',
    inputLabel: 'CNPJ da Empresa',
    inputHelper: '14 dígitos cadastrais do CNPJ sem pontuação (ex: 12345678000190)',
  },
  {
    id: 'pro_titulo',
    title: 'Título Pro',
    subtitle: 'Dados do título de eleitor',
    command: '/titulo',
    placeholder: '123456780191',
    badge: 'ELEITORAL',
    iconName: 'Vote',
    description: 'Situação eleitoral na Justiça Eleitoral, zona, seção, município de votação e status da biometria.',
    defaultSample: '123456780191',
    inputLabel: 'Número do Título de Eleitor',
    inputHelper: '12 dígitos numéricos do título de eleitor (ex: 123456780191)',
  },
  {
    id: 'pro_mae',
    title: 'Mãe Pro',
    subtitle: 'Busca pelo nome da mãe',
    command: '/mae',
    placeholder: 'Maria Silva Santos',
    badge: 'FILIAÇÃO',
    iconName: 'HeartHandshake',
    description: 'Cruzamento genealógico familiar, filhos vinculados, provável CPF da genitora e endereços de contato.',
    defaultSample: 'Maria Silva Santos',
    inputLabel: 'Nome Completo da Mãe',
    inputHelper: 'Nome completo da genitora (ex: Maria Silva Santos)',
  },
  {
    id: 'pro_foto',
    title: 'Foto Pro',
    subtitle: 'Foto cadastral',
    command: '/foto',
    placeholder: '12345678901',
    badge: 'BIOMETRIA',
    iconName: 'Camera',
    description: 'Localização de registro fotográfico oficial (CNH Digital, DNI, RG) e score de autenticidade biométrica.',
    defaultSample: '12345678901',
    inputLabel: 'CPF para Busca de Foto',
    inputHelper: '11 dígitos numéricos do CPF do alvo (ex: 12345678901)',
  },
  {
    id: 'pro_placa',
    title: 'Placa Pro',
    subtitle: 'Relatório veicular completo',
    command: '/placa',
    placeholder: 'AAA9999',
    badge: 'VEICULAR VIP',
    iconName: 'CarFront',
    description: 'Histórico completo do veículo, chassi, Renavam, multas, débitos, alienação fiduciária e proprietário.',
    defaultSample: 'AAA9999',
    inputLabel: 'Placa do Veículo',
    inputHelper: 'Placa sem hífen (ex: AAA9999 ou ABC1D23)',
  },
];
